### ISSUE TITLE
Ionic: @ionic-native/appsflyer is out of date with all latest features and breaking changes

### ISSUE THREAD

**Issue by bobrosoft** [AppsFlyerSDK/appsflyer-cordova-plugin#103]
Hi there. Please update @ionic-native/appsflyer with latest breaking changes and new options like waitForATTUserAuthorization.
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/appsflyer/index.ts#L4

Thanks.

**Comment by mariusbolik** [comment]
You can use it like this as long as the plugin isn't updated:
```ts
async initAppsFlyer() {
  try {
    await this.platform.ready();
    if (this.platform.is('cordova')) {
      await this.appsflyer.initSdk({
        devKey: '*****',
        appId: '*******',
        isDebug: false,
        waitForATTUserAuthorization: 10,
      } as any);
    }
  } catch (error) {
    console.error(error);
  }
}
```
I also submitted a pull request: https://github.com/ionic-team/ionic-native/pull/3541
