### ISSUE TITLE
Release with getReferrer feature

### ISSUE THREAD

**Issue by dmitryuk** [AppsFlyerSDK/appsflyer-cordova-plugin#110]
Hello,
The pr https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/106 was merged, but it hasn't still been released.
Current release is 6.0.50
Please make a new release.

**Comment by amit-kremer93** [comment]
Hi @dmitryuk new release with your code will be publish soon

**Comment by amit-kremer93** [comment]
Hi @dmitryuk 
please read my comment here: #114
