### ISSUE TITLE
Playmarket empty response from getReferer

### ISSUE THREAD

**Issue by turboasm** [AppsFlyerSDK/appsflyer-cordova-plugin#114]
Latest release with MR https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/109/files updated com.android.installreferrer:installreferrer from 1.1.2 to 2.1,
New implementation doesn't call AppsFlyerProperties.getInstance().setReferrer() internally, so AppsFlyerProperties.getInstance().getReferrer() method always returns empty response.

**Comment by af-fess** [comment]
hey @turboasm. Why do you need  `AppsFlyerProperties.getInstance().setReferrer()`?
The native SDK collects google install referrer on start.

**Comment by dmitryuk** [comment]
I think because this method uses `getReferrer` of SDK
https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/106

**Comment by turboasm** [comment]
@af-fess How we can gather the referrer from SDK?
for example, the code was working until the com.android.installreferrer:installreferrer has not been updated
<code>
plugin.initSdk({
                        devKey: window.config.appFlyerSdk.key,
                        isDebug: true,
                        onInstallConversionDataListener: true
                    },
                    (result) => {
 // todo: getReferrer
}...
</code>

**Comment by amit-kremer93** [comment]
Hi @turboasm @dmitryuk 
The methods `AppsFlyerProperties.getInstance().getReferrer()` and `AppsFlyerProperties.getInstance().setReferrer()` are old methods that were used before the update of installReferrer and other logic on the native sdk.
After talking with our PM i was told that these methods are going to be deprecated and not to add them to the plugin as well.
Thank you for your understanding.
