### ISSUE TITLE
Cannot build 6.0.50 on Android - Missing symbol

### ISSUE THREAD

**Issue by vandres** [AppsFlyerSDK/appsflyer-cordova-plugin#115]
# Report
When I try to build the plugin for Android, I get the following error:

```
/Users/vandres/Resourcen/www/wflwrapp2.0/platforms/android/app/src/main/java/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:817: error: cannot find symbol
        AppsFlyerLib.getInstance().registerValidatorListener(this.cordova.getContext(), new AppsFlyerInAppPurchaseValidatorListener() {
                                                                                            ^
  symbol:   class AppsFlyerInAppPurchaseValidatorListener
  location: class AppsFlyerPlugin
```

Using 6.0.30 it still works. We are having a targetSdk of "30", if that matters.

## Plugin Version

6.0.50

## On what Platform are you having the issue?

Cordova Android 9.0.0

## What did you do?

`ionic cordova run android`

## What did you expect to happen?

App builds

## What happened instead?

Build fails with the error message already mentioned

## Please provide any other relevant information.

Cordova v10
Cordova Android v9
targetSdk 30

**Comment by amit-kremer93** [comment]
Hi @vandres thank you for opening this issue.
it happens because of a missing import and will be fixed soon.
meanwhile you can fix it in your machine according to [this](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/113) MR
sorry for the inconvenience.

**Comment by vandres** [comment]
@amit-kremer93 We are having an automated build process. Is there any ETA for the fix release?

**Comment by amit-kremer93** [comment]
@vandres by tomorrow. Hopefully sooner

**Comment by vandres** [comment]
@amit-kremer93 Thanks for the info

**Comment by amit-kremer93** [comment]
Hi @vandres . i released 6.0.51 with fix.
https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/117

**Comment by vandres** [comment]
Thanks. I will test the next days.

**Comment by vandres** [comment]
@amit-kremer93 I can build with 6.0.51. Thanks for the quick fix
