### ISSUE TITLE
Use of undeclared identifier 'afNoDomains'

### ISSUE THREAD

**Issue by gadapa-rakesh** [AppsFlyerSDK/appsflyer-cordova-plugin#123]
# Report

## Plugin Version
6.0.52

## On what Platform are you having the issue?
iOS

## What did you do?
XCode Build

## Please provide any other relevant information.
`AppsFlyerPlugin.h` is missing `afNoDomains` variable declaration causing build time errors. Looks like it was missed part of this [commit](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/commit/3da2ffd464c6ac13e82ee633c1bf720ae9199300?branch=3da2ffd464c6ac13e82ee633c1bf720ae9199300&diff=split)

**Comment by amit-kremer93** [comment]
Hi @gadapa-rakesh thank you for opening this issue. it will be fixed soon!

**Comment by amit-kremer93** [comment]
https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/124

**Comment by gadapa-rakesh** [comment]
Thank you @amit-kremer93!
