### ISSUE TITLE
For iOS, why logEvent fires 2 [AppsFlyerLib shared] logEvent?

### ISSUE THREAD

**Issue by jamesyoon11** [AppsFlyerSDK/appsflyer-cordova-plugin#128]
# Report

## Plugin Version

master

## On what Platform are you having the issue?

iOS

## What did you do?

npm fetch

## What did you expect to happen?

1 `[AppsFlyerLib shared] logEvent` 

## What happened instead?

2 `[AppsFlyerLib shared] logEvent`

## Please provide any other relevant information.

Please see

https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/src/ios/AppsFlyerPlugin.m#L232

and 

https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/src/ios/AppsFlyerPlugin.m#L239

**Comment by af-fess** [comment]
Good catch @jamesyoon11 . Will be fixed in 24 hours.

**Comment by amit-kremer93** [comment]
@jamesyoon11 fixed. thank you! https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/pull/130
