### ISSUE TITLE
[Ionic 4/Cordova] Build issue on iOS

### ISSUE THREAD

**Issue by Galiza** [AppsFlyerSDK/appsflyer-cordova-plugin#131]
# Report

## Plugin Version
6.1.11

## On what Platform are you having the issue?
iOS

## What did you do?
Run **ionic cordova build ios --device --release --prod -- --buildConfig build.json**

## What did you expect to happen?
The .ipa to be generated correctly.

## What happened instead?
We got the following error:
> ld: warning: ignoring file /usr/lib/libstdc++.6.0.9.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64 Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_AppsFlyerCrossPromotionHelper", referenced from:       objc-class-ref in AppsFlyerPlugin.o   "_OBJC_CLASS_$_AppsFlyerShareInviteHelper", referenced from:       objc-class-ref in AppsFlyerPlugin.o   "_OBJC_CLASS_$_AppsFlyerLib", referenced from:       objc-class-ref in AppsFlyerPlugin.o       objc-class-ref in AppsFlyerX+AppController.o ld: symbol(s) not found for architecture arm64

## Please provide any other relevant information.
The issue happened when we first ran on iOS, Android builds and works fine, it does generate the .apk correctly.

**Comment by amit-kremer93** [comment]
@Galiza did you try to build it directly from Xcode?

**Comment by Galiza** [comment]
@amit-kremer93 No, as we actually use a Jenkins machine that runs the ionic command. So the .ipa is generated through the command, not from XCode.

**Comment by amit-kremer93** [comment]
@Galiza I sent the solution through our support team. If you have any questions, please feel free to contact support@apppsflyer.com

**Comment by vlad-grigoryan** [comment]
@amit-kremer93 Can you send me solution also, I have the same issue on ionic 3

**Comment by rajparekh07** [comment]
@amit-kremer93 Please post the solution, its falling for us too. [Compiling via xcbuild and xcode ui both]

**Comment by amit-kremer93** [comment]
@vlad-grigoryan @rajparekh07 please share on which iOS version, xcode version and cordova version you are facing the problem

**Comment by rajparekh07** [comment]
Xcode 12.4, iOS 14.5.1, Cordova 8 and cordova ios 6.1 @amit-kremer93

**Comment by dalybouba** [comment]
no solution  untill now???
