### ISSUE TITLE
iOS app stuck at the splash screen

### ISSUE THREAD

**Issue by cristianizzo** [AppsFlyerSDK/appsflyer-cordova-plugin#146]
# Report
iOS app stuck at the splash screen after installed the AppsFlyer SDK

## Plugin Version
cordova-plugin-appsflyer-sdk@6.2.20
@ionic-native/appsflyer@5.31.1

## On what Platform are you having the issue?
iOS

## What did you do?
I follow the documentation https://ionicframework.com/docs/native/appsflyer

npm install cordova-plugin-appsflyer-sdk
npm install @ionic-native/appsflyer
ionic cap sync
ng build ---configuration=development

then in Xcode, I run the app and below the screenshot of the logs

<img width="736" alt="Screenshot 2021-02-17 at 20 09 31" src="https://user-images.githubusercontent.com/5518760/108256076-552f6a00-715d-11eb-94ad-618e1cae5970.png">

## What did you expect to happen?
Ionic app to run 

## What happened instead?
Ionic app stuck at the splash screen 

I am trying to integrate AppsFlyer on an existing ionic app

**Comment by amit-kremer93** [comment]
@cristianizzo in Android it works fine? did you initialize our SDK inside `this.platform.ready().then(()...` as our [guide](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin#2---using-ionic-native-plugin) says?
