### ISSUE TITLE
Android build fails with the v6.2.40 using the Capacitor

### ISSUE THREAD

**Issue by vildhjarta8** [AppsFlyerSDK/appsflyer-cordova-plugin#153]
# Report

## Plugin Version

6.2.40

## On what Platform are you having the issue?

android

## What did you do?

Trying to build the application

## What did you expect to happen?

Application was built

## What happened instead?

Build fails with given error:
`
/.../android/capacitor-cordova-android-plugins/src/main/java/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:37: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/.../android/capacitor-cordova-android-plugins/src/main/java/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:282: error: cannot find symbol
            public void onDeepLinking(@NonNull DeepLinkResult deepLinkResult) {
                                       ^
  symbol: class NonNull
`

## Please provide any other relevant information.

I was upgraded AppsFlyer to the latest version in order to use the ATT for an iOS 14.5, but after this, my android builds started to fail.
I'm using Capacitor instead of Cordova.
`@capacitor/core` and `@capacitor/android` are up to date, v2.4.7.

Also, I tried to install the `cordova-plugin-androidx-adapter` and Capacitor sees it as an Android plugin, but still no luck, it doesn't help.

**Comment by vildhjarta8** [comment]
Jetifier resolves the issue.

**Comment by AlibekJ** [comment]
Replace
```import android.support.annotation.NonNull```
with
```import androidx.annotation.NonNull``` 
in all the copies of AppsFlyerPlugin.java
