### ISSUE TITLE
"Didn't find class "com.appsflyer.AppsFlyerLib" error was reported after upgraded to version 6.2.3

### ISSUE THREAD

**Issue by zengjie-android** [AppsFlyerSDK/appsflyer-cordova-plugin#159]
I need to upgraded appsflyer sdk to version 6.2.3 and got this error: 
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appsflyer.AppsFlyerLib" on path: DexPathList[[zip file "/data/app/~~FvFWLvnrVtldkS2_TMEW8g==/com.uxin.live.overseas-FBcwFccULnUTK2Px3ww7kw==/base.apk"],nativeLibraryDirectories=...

my code is below.
build.gradle:
dependencies {
    implementation 'com.appsflyer:af-android-sdk:6.2.3'
    implementation 'com.android.installreferrer:installreferrer:1.0'
}

proguard.cfg:
-dontwarn com.android.installreferrer
-keep class com.appsflyer.** { *; }

and the initialization part is the same as the official recommendation.Now I have no solution to the problem,so I will be very grateful for any help!

**Comment by amit-kremer93** [comment]
@zengjie-android thank you for opening this issue. did you upgrade from earlier sdk version? if yes, which version?
