### ISSUE TITLE
After 6.2.60 update project can't be built anymore

### ISSUE THREAD

**Issue by BigBerny** [AppsFlyerSDK/appsflyer-cordova-plugin#162]
# Report

## Plugin Version

6.2.60

## On what Platform are you having the issue?

ios

## What did you do?

I updated the plugin by running "npm install cordova-plugin-appsflyer-sdk". I even tried to uninstall and reinstall.

## What did you expect to happen?

After updating from 6.2.42 to 6.2.60 it should still be able to build. Before it was building perfectly. 

## What happened instead?

        [!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
        In Podfile:
        CordovaPluginsStatic (from `../capacitor-cordova-ios-plugins`) was resolved to 3.0.0-rc.0, which depends on
        AppsFlyerFramework (= 6.2.6)
        
        None of your spec sources contain a spec satisfying the dependency: `AppsFlyerFramework (= 6.2.6)`.

## Please provide any other relevant information.

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.5
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 3.0.0-rc.0
   @capacitor/core : 3.0.0-rc.0

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.3.0

System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 6.14.10
   OS     : macOS Big Sur

**Comment by d4nshields** [comment]
Hi, I ran into a similar problem but found that there is a workaround:

cd platforms/ios; pod install --repo-update; cd ../..

Then I remove the plugin and re-try from the plugin install step.

**Comment by amit-kremer93** [comment]
Hi, Try to remove the plugin completely, also the podfile.lock file and then install the plugin again

**Comment by BigBerny** [comment]
I tried to remove and reinstall the plugin but it didn't work. Will have a look at podfile.lock

**Comment by mariusbolik** [comment]
I get the following error using cordova:

<img width="571" alt="Bildschirmfoto 2021-05-11 um 16 05 50" src="https://user-images.githubusercontent.com/39862171/117829182-cec58880-b272-11eb-9b93-0c641a44a728.png">

**Comment by amit-kremer93** [comment]
@mariusbolik most of the problems after upgrading versions can be solved by clean the project + remove derived data and then build again

**Comment by mariusbolik** [comment]
> @mariusbolik most of the problems after upgrading versions can be solved by clean the project + remove derived data and then build again

Yes! Issue was gone after removing the ios project an adding it again :)
