### ISSUE TITLE
Support for AppsFlyerFramework/Strict

### ISSUE THREAD

**Issue by BigBerny** [AppsFlyerSDK/appsflyer-cordova-plugin#164]
Because of the new Apple guidelines would be awesome if a fork that uses "AppsFlyerFramework/Strict" instead the of standard one: https://support.appsflyer.com/hc/en-us/articles/207032066#additional-apis-strict-mode-sdk

Best
Janis

**Comment by pazlavi** [comment]
@BigBerny 
Hi Janis, 

Thank you for contacting us.

Did you check our [documentation](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin#-add-or-remove-strict-mode-for-app-kids) on how to switch to the strict mode? 
If your app is not in the kids category, you may use our regular SDK.
