### ISSUE TITLE
AppsFlyer breaks deeplinks intended for @ionic-native/deeplinks on iOS

### ISSUE THREAD

**Issue by MichaelAshf** [AppsFlyerSDK/appsflyer-cordova-plugin#172]
# Report

When AppsFlyer Cordova Plugin is installed in an Ionic 3 project, alongside @ionic-native/deeplinks, tapping a link intended to be handled by Ionic Native Deeplinks, gets intercepted  by AppsFlyer, it appears as though it is mistaken for an "onAppOpenAttribution" deeplink.

## Plugin Version

6.3.0

## On what Platform are you having the issue?

iOS

## What did you do?

Install AppsFlyer Cordova and Ionic Native Deeplinks
Configure Ionic app to respond to deeplinks
Click on a link associated with domain registered for deeplinks

## What did you expect to happen?

Deeplink should be handled by Ionic-Native/Deeplinks

## What happened instead?

Subscribing to deeplinks detected no deeplinks.
AppsFlyer SDK outputs the following:

`2021-06-09 12:04:59.529916+0100 Wealthify[7885:3580042] jsonMessageStr = {"status":"success","type":"onAppOpenAttribution","data":{"scheme":"https","link":"https:\/\/obfuscated\/deeplink\/test","host":"obfuscated","path":"\/deeplink\/test"}}`

## Please provide any other relevant information.

Reverting to version 6.1.10 resolves the issue.

**Comment by pazlavi** [comment]
Hi @MichaelAshf 
Thank you for reaching out to us.

Since V6.3.0, the plugin will resolve and process the deep link in IOS automatically without adding code to the `AppDelegate` file. 
To disable it, please comment out the methods in [this file](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/src/ios/AppsFlyerX%2BAppController.m#L13-L26) and paste them into your `AppDelegate` file.

**Comment by rajparekh07** [comment]
Thanks @pazlavi that does work but how do fix this in a better way, let's say for CD / CI where this plugin would automatically installed?

**Comment by pazlavi** [comment]
Hi @rajparekh07,
Until our latest version (6.3.0), the only way to use deep links with our plugin was by adding code to the AppDelegate file.
In the last version, we added the ability to resolve the deep links without adding any code to the AppDelegate file.
The upcoming release will probably add the ability to disable the automatically deep links resolving but in that case, you'll need to implement the deep linking logic by yourself on the native side.
We'll try to add more flexible deep link options in future releases but we can't commit on a timeline.
