### ISSUE TITLE
Build fails for iOS (arm64) 

### ISSUE THREAD

**Issue by DaedalusAB** [AppsFlyerSDK/appsflyer-cordova-plugin#175]
# Report

## Plugin Version

 "cordova-plugin-appsflyer-sdk": "^6.3.20",

## On what Platform are you having the issue?

iOS
Ionic 4
cordova-ios 6.2.0  (and 6.1.0)

## What did you do?

Build fails for iOS at xCode

## What did you expect to happen?

Build to not fail 

## What happened instead?

Build failed with this:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AppsFlyerCrossPromotionHelper", referenced from:
      objc-class-ref in AppsFlyerPlugin.o
  "_OBJC_CLASS_$_AppsFlyerShareInviteHelper", referenced from:
      objc-class-ref in AppsFlyerPlugin.o
  "_OBJC_CLASS_$_AppsFlyerLib", referenced from:
      objc-class-ref in AppsFlyerPlugin.o
      objc-class-ref in AppsFlyerAttribution.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pazlavi** [comment]
Hi @DaedalusAB, 
Thank you for reaching out to us. 

Your issue is similar to #162. 
The issue is not directly related to the SDK. It is an issue with your compiler and linker. 
Up to version 6.0.54, the plugin used our static lib SDK, and since version 6.1.10, we are using CocoaPods.

**Comment by DaedalusAB** [comment]
Hi @pazlavi 

Thanks for linking it.
During my build process, there is no iOS project/platform to begin with - so the solution from #162 doesn't work.
Also, I did not update the plugin, I've started with this version from scratch. 
Any other tips?

**Comment by pazlavi** [comment]
Hi @DaedalusAB 
Please check these StackOverflow threads that may help: https://stackoverflow.com/a/26903572  https://stackoverflow.com/a/63955114.

I'm not familiar with other solutions. It is something with your environment configuration.
