### ISSUE TITLE
pls update documentation for cordova plugin API

### ISSUE THREAD

**Issue by expcapitaldev** [AppsFlyerSDK/appsflyer-cordova-plugin#177]
https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/docs/API.md - old documentation, pls update

**Comment by pazlavi** [comment]
Hi @expcapitaldev ,
Thank you for reaching out to us.

We started the process of updating the documentation for all of our plugins. It will take a few weeks.
