### ISSUE TITLE
Cannot compile with xcode to iphone

### ISSUE THREAD

**Issue by bboldi** [AppsFlyerSDK/appsflyer-cordova-plugin#187]
# Report

I get this error when trying to compile app in xcode

```
In /Users/user/Library/Developer/Xcode/DerivedData/App-eismujpzjeytykgfdircgvnuefmj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib(AFSDKDevice.o), building for iOS, but linking in object file (/Users/user/Library/Developer/Xcode/DerivedData/App-eismujpzjeytykgfdircgvnuefmj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib(AFSDKDevice.o)) built for Mac Catalyst, file '/Users/user/Library/Developer/Xcode/DerivedData/App-eismujpzjeytykgfdircgvnuefmj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib' for architecture arm64
```
have tried different solution, like changing the `ONLY_ACTIVE_ARCH = YES` and `NO` then adding EXCLUDED_ARCHS arm64 , and so on, but nothing helps ...

## Plugin Version

ℹ Please replace these two lines with the plugin version.

`appsflyer-capacitor-plugin@6.4.0`

## On what Platform are you having the issue?

ios 14

**Comment by pazlavi** [comment]
Hi @bboldi ,
Thank you for reaching out to us.

The issue sounds similar to this: https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/173
Please make sure that you are using the latest Cocoapods version as we use `xcframework` for iOS platform.

**Comment by bboldi** [comment]
Unfortunately did not help ... I opened another ticket, because I'm using capacitor, not cordova ... https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/issues/8 

Thanks!
