### ISSUE TITLE
Retrieving attribution data after invited user install

### ISSUE THREAD

**Issue by ghonche-yqr** [AppsFlyerSDK/appsflyer-cordova-plugin#188]
# Report

## Plugin Version

@ionic-native/appsflyer: 5.36.0

## On what Platform are you having the issue?

Android

## What did you do?

I've generated an invitation link using `generateInviteLink(options)`. (for example: https://lifa.onelink.me/AdfR/515dad80) When the app is already installed on device, this link opens the app and triggers `registerOnAppOpenAttribution()` event.
But when app is not installed on device, the link opens my app's page on Google Play, which is actually fine. 

## What did you expect to happen?

I expect the `registerOnAppOpenAttribution()` (or any other event) triggers when user finishes installation via invite link and opens the app for the first time from Google Play.

## What happened instead?

No event is called.

## Please provide any other relevant information.

I guess the `onConversionDataSuccess()`  should be a good solution to my problem. but unfortunately there is no implementation on Cordova for this.

Any help is appreciated.

**Comment by pazlavi** [comment]
Hi @ghonche-yqr,
Thank you for reaching out to us.

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
