### ISSUE TITLE
Cannot find a way to Set Partner Data to close the loop of callbacks to Braze(formerly AppBoy)

### ISSUE THREAD

**Issue by muhammad-omar** [AppsFlyerSDK/appsflyer-cordova-plugin#189]
# Report

## Plugin Version

6.4.0

## On what Platform are you having the issue?

ios and android

## What did you do?

Check the Plugin Cordova exposed interface and the method is not there

## What did you expect to happen?

In reference to [this link](https://www.braze.com/docs/partners/message_orchestration/attribution/appsflyer/appsflyer_audiences/#appsflyer-and-braze-cohort-import)
Avail the method "setPartnerData" to use to for Braze integration callbacks

## What happened instead?

Cannot use the full cycle now for callbacks on Braze

**Comment by pazlavi** [comment]
Hi @muhammad-omar,
Thank you for reaching out to us.

We will do our best to include this additional API in the upcoming release.

**Comment by ghobashy** [comment]
@pazlavi do you know when this feature will be released?
