### ISSUE TITLE
setAppUserId and getAppsFlyerUID relation

### ISSUE THREAD

**Issue by juanico18** [AppsFlyerSDK/appsflyer-cordova-plugin#201]
# Report

## Plugin Version

6.4.4

## On what Platform are you having the issue?
ios and android

## What did you do?

We are using cordova appsflyer integration.
By one side we are calling to setAppUserId  to ser our customerUserId then we call getAppsFlyerUID

## What did you expect to happen?
 get customerUserId on getAppsflyerUID

## What happened instead?

 we are not getting our customerUserId, we are getting other value: 1646825633403-5879522

## Please provide any other relevant information.

Is this normal?

**Comment by pazlavi** [comment]
Hi @juanico18, 
Thank you for reaching out to us.

Yes, this is normal. The `getAppsFlyerUID` method returns the AppsFlyer ID that is automatically created for every new install of an app.
You can find more info [here](https://support.appsflyer.com/hc/en-us/articles/4408847686161-Device-identifiers#device-identifiers-for-all-platforms).
