### ISSUE TITLE
[bug xml config-file] config file undefined requested for changes not found

### ISSUE THREAD

**Issue by expcapitaldev** [AppsFlyerSDK/appsflyer-cordova-plugin#213]
# Report
`cordova prepare android --verbose`

Installing "cordova-plugin-appsflyer-sdk" for android
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-appsflyer-sdk on android platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-appsflyer-sdk" on android.
Beginning processing of action stack for android project...
Installing Android library: src/android/cordovaAF.gradle
Action stack processing complete.
**config file undefined requested for changes not found at /builds/frontend/station-ws/apps/trading-mobile-phone-cx/platforms/android/undefined, ignoring
config file undefined requested for changes not found at /builds/frontend/station-ws/apps/trading-mobile-phone-cx/platforms/android/undefined, ignoring
config file undefined requested for changes not found at /builds/frontend/station-ws/apps/trading-mobile-phone-cx/platforms/android/undefined, ignoring**

## Plugin Version
6.8.2

## On what Platform are you having the issue?
android

## What did you do?
`cordova prepare android --verbose`

## What did you expect to happen?
AndroidManifest.xml  does not have tags `uses-permission` from your  plugin.xml
because your code see https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/6.8.2/plugin.xml#L50 is wrong after release new `cordova-common` version 4.1.0.
I checked with version `cordova-common` 4.0.2 it is worked, did not work with 4.1.0, because `cordova` version used see https://github.com/apache/cordova-cli/blob/master/package.json#L26 "^4.0.2"
AndroidManifest.xml should have `uses-permission`  from your plugin
Also,  looks like you can not use 'mode' attribute inside `config-file` see https://cordova.apache.org/docs/en/11.x/plugin_ref/spec.html#config-file

## What happened instead?

see information above

## Please provide any other relevant information.

see logs above

**Comment by expcapitaldev** [comment]
any updates here?

**Comment by pschinis** [comment]
Are there any plans to merge this fix? The plugin literally doesn't work on Android right now because of this issue. Would prefer not to have to create my own fork to get it working
