### ISSUE TITLE
Issue building Ionic Cordova app for Android

### ISSUE THREAD

**Issue by DonWono** [AppsFlyerSDK/appsflyer-cordova-plugin#86]
# Report
When building the Ionic Cordova App for Android, we ran into a build failed issue after installing and adding AppsFlyer. We installed the plugin from the documentation.

$ ionic cordova plugin add cordova-plugin-appsflyer-sdk
$ npm install @ionic-native/appsflyer

After installing and building, the build failed. This is the output from our terminal:

`
.../AppsFlyerPlugin.java:472: error: local variable parameters is accessed from within inner class; needs to be declared final
				String token = parameters.optString(0);
				               ^
.../AppsFlyerPlugin.java:476: error: local variable callbackContext is accessed from within inner class; needs to be declared final
					callbackContext.success(SUCCESS);
					^
.../AppsFlyerPlugin.java:479: error: local variable callbackContext is accessed from within inner class; needs to be declared final
					callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.ERROR, "Not a valid token"));`

## Plugin Version

 `4.11.0`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
android

## What did you do?

ℹ Please replace these two lines with what you did.  
First we installed the plugin using the following commands:
$ ionic cordova plugin add cordova-plugin-appsflyer-sdk
$ npm install @ionic-native/appsflyer

We setup the plugin as suggested in the documentation.

Then we build the app with the following command:
ionic cordova build android --release --prod

## What did you expect to happen?
We expected the app to build successfully.

## What happened instead? 
The build failed.

**Comment by af-fess** [comment]
@DonWono thank you, we will check it out

**Comment by amit-kremer93** [comment]
@DonWono the bug i fixed
