### ISSUE TITLE
Google CID dublicate data reporting

### ISSUE THREAD

**Issue by dmitryuk** [AppsFlyerSDK/appsflyer-cordova-plugin#89]
# Report

## Plugin Version

4.4.16

## On what Platform are you having the issue?

Android

## What did you do?

Installed and initialized the plugin after GA is.

## What happened instead?

Data in GA is duplicated, ga analytics shows like a lot of new visitors came with http-kit WebBrowser.
![image](https://user-images.githubusercontent.com/661654/74715483-11aad300-525f-11ea-82e9-47ed20a77247.png)

As I understood, to avoid that you suggest to do following:
![image](https://user-images.githubusercontent.com/661654/74715605-53d41480-525f-11ea-81e0-0240c2c90bfd.png)
How correctly  to  configure the plugin with GA?

**Comment by af-fess** [comment]
In order for us to provide optimal support, we would kindly ask you to submit any issues to support@appsflyer.com
