### ISSUE TITLE
initSdk not returning any response i.e no sucess or failure

### ISSUE THREAD

**Issue by mineexcellence** [AppsFlyerSDK/appsflyer-cordova-plugin#94]
# Report

## Plugin Version

cordova -plugin-appsflyer-sdk - 5.2.1

## On what Platform are you having the issue?
e.g. android only.On Ios its working 
and I am using ionic 4

## What did you do?
I am using it for ionic . So as mentioned in documentation, i did below steps

1) Installed the plugin using 
ionic cordova plugin add cordova-plugin-appsflyer-sdk
npm install @ionic-native/appsflyer

2) Added below code on when device ready
 var options = {
        devKey: 'XXXXXXXXXXX', // your AppsFlyer devKey
        isDebug: true,
        appId: 'XXXXXXXX' // your ios appID           
      };
this.appsflyer.initSdk(options).then(result=>{
        console.log("success appssflyer");
 },error=>{
    console.log("error  appsflyer");
    console.error(error);
  }); //AppsFlyer
## What did you expect to happen?
It should either sucess or some failure 

## What happened instead?
No response from initSdk function

## Please provide any other relevant information.

I have looked at simlar issues raised here but didnt get anu helpful informatin to proceed. In ios its working good but issues is only with android.

**Comment by marc0n3** [comment]
I got the same issue.
I'm developing an Android app.
Inside Android studio I got:
` D/AppsFlyer: Executing...
D/AppsFlyer: Starting Tracking
D/AppsFlyer_5.2.0: Initializing AppsFlyer SDK: (v5.2.0.311)
I/AppsFlyer_5.2.0: getDeepLinkData with activity null
I/AppsFlyer_5.2.0: Allowing multiple launches within a 5 second time window.
I/AppsFlyer_5.2.0: sendTrackingWithEvent from activity: android.app.Application
I/AppsFlyer_5.2.0: Trying to fetch GAID..
I/AppsFlyer_5.2.0: ******* sendTrackingWithEvent: Launch
W/AppsFlyer_5.2.0: Permission android.permission.ACCESS_WIFI_STATE is missing in the AndroidManifest.xml
I/AppsFlyer_5.2.0: IMEI was not collected.
I/AppsFlyer_5.2.0: Android ID was not collected.
I/AppsFlyer_5.2.0: AppsFlyer: first launch date: 2020-04-23_084357+0000
D/AppsFlyer_5.2.0: didConfigureTokenRefreshService=false
D/AppsFlyer_5.2.0: No deep link detected
I/AppsFlyer_5.2.0: AppsFlyerLib.sendTrackingWithEvent
I/AppsFlyer_5.2.0: url: https://launches.appsflyer.com/api/v5.2/androidevent?app_id=com.XXXXXX.app&buildnumber=5.2.0
I/AppsFlyer_5.2.0: data: {"country":"IT","af_timestamp":"1587633258412","appsflyerKey":"s********************Y","af_events_api":"1","isFirstCall":"true","registeredUninstall":false,"cell":{"mnc":10,"mcc":222},"operator":"ho.","network":"WIFI","timepassedsincelastlaunch":"23","open_referrer":"","af_v2":"xxxxxxx","sig":"xxxxxx","uid":"xxxxxx,"isGaidWithGps":"true","lang_code":"it","installDate":"2020-04-23_082846+0000","app_version_code":"101153","firstLaunchDate":"2020-04-23_084357+0000","ivc":false,"model":"SM-A320FL","lang":"italiano","brand":"samsung","deviceType":"user","last_boot_time":1582484959486,"product":"a3y17ltexc","kef7366":"xxxx","deviceData":{"cpu_abi":"armeabi-v7a","build_display_id":"xxxxxxx","btch":"no","dim":{"size":"2","ydp":"309.638","xdp":"309.966","y_px":"1280","x_px":"720","d_dpi":"280"},"arch":"","btl":"100.0","cpu_abi2":"armeabi"},"date2":"2020-04-23_104222+0200","counter":"16","date1":"2020-04-23_102846+0200","advertiserId":"xxxx","advertiserIdEnabled":"true","af_v":"xxxxxxx","carrier":"ho.","disk":"610\/10165","af_preinstalled":"false","iaecounter":"2","sc_o":"p","tokenRefreshConfigured":false,"sdk":"26","appUserId":"xxxxxx","app_version_name":"0.0.23","device":"a3y17lte","platformextension":"android_cordova","cksm_v1":"xxxxx"}
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
I/AppsFlyer_5.2.0: response code: 404`

 https://launches.appsflyer.com is unreachable from my browser, I'm in italy.

Maybe this helps,
Thanks in advance

**Comment by amit-kremer93** [comment]
@mineexcellence @marc0n3 I'm checking it

**Comment by amit-kremer93** [comment]
1. @mineexcellence please run the init function like that:
`this.appsflyer.initSdk(options).then(result=>{
      console.log(result);
      });`
and send me the log.
2. @marc0n3 please send me your `devkey` and your `app_id` for further check to Amit.kremer@appsflyer.com

**Comment by mineexcellence** [comment]
Thanks for your reply.
I have responded to your email with detais.

**Comment by amit-kremer93** [comment]
@marc0n3 [](https://support.appsflyer.com/hc/en-us/articles/360001559405-Testing-AppsFlyer-SDK-integration#debugging)
try this and let me know if it helped

**Comment by marc0n3** [comment]
Thank you @amit-kremer93!
It was my fault, to make log work with android studio debug app I have to create a new app in your platform of type "Pending approval or unpublished"

**Comment by marc0n3** [comment]
@amit-kremer93 actually, logging is happening but no result nor error comes to javascript as result of init.
`   instance.startTracking(c.getApplication(), devKey, new AppsFlyerTrackingRequestListener() {
                    @Override
                    public void onTrackingRequestSuccess() {
                        callbackContext.success(SUCCESS);
                    }

                    @Override
                    public void onTrackingRequestFailure(String s) {
                        callbackContext.success(FAILURE);
                    }
                });`

is executed but the debugger is not stopping inside onTrackingRequestSuccess nor onTrackingRequestFailure.
Thanks
