### ISSUE TITLE
onAppOpenAttribution callback not handled correctly first time on resume

### ISSUE THREAD

**Issue by jskrepnek** [AppsFlyerSDK/appsflyer-cordova-plugin#97]
# Report

## Plugin Version

5.2.2

## On what Platform are you having the issue?

Android and probably iOS

## What did you do?

- Open app with plugin installed
- Background app
- Resume app from deep link

## What did you expect to happen?

- deep link data returned via onAppOpenAttribution callback

## What happened instead?

- deep link data returned via onConversionDataSuccess callback

## Please provide any other relevant information.

This is caused by the on resume handling, when there is no previous intent - i.e.: the first time a deep link resumes the app, when it is already open.  

When a deep link is clicked the app resumes.  The on resume handler processes this by [overwriting the attribution data listener with the given call back context](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/src/android/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java#L572).  This prevents the onAppOpenAttribution callback from being able to correctly process the subsequent deep link handling.

What problem is the on resume handling meant to solve?  Is it safe to remove?

**Comment by amit-kremer93** [comment]
Hi @jskrepnek ! thank you for opening this issue.
 i will examine it and keep you up to date

**Comment by amit-kremer93** [comment]
Hi @jskrepnek , i released a new version of the plugin (6.2.0) with a fix for this problem. please notice that the implementation has slightly changed so please read [this](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/docs/Guides.md#handle-deeplinking). if there is any problem please contact us!
